- name: Install zsh
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - fzf
    - zsh

- name: Install tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - direnv

- name: Setup default shell
  become: true
  ansible.builtin.user:
    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: /usr/bin/zsh

- name: Setup config dir
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
    state: directory
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0700'

- name: Install Config
  ansible.builtin.synchronize:
    src: "zsh"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
    mode: push
    delete: true
    archive: true
    recursive: true

- name: Copy Secret
  ansible.builtin.copy:
    src: "zsh/secrets.zsh"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/zsh/secrets.zsh"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'

- name: Copy hidden config
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: '0644'
