- name: Uninstall apt tmux
  when: ansible_os_family != 'Darwin'
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Install tmux
  community.general.homebrew:
    name: tmux
    state: present
  become: false

- name: Install tmux package manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux/plugins/tpm"
    update: true
    clone: true

- name: Setup tmux configs
  ansible.builtin.synchronize:
    src: "tmux"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"
    mode: push
    delete: true
    archive: true
    recursive: true
# - name: Install tmux conf
#   ansible.builtin.copy:
#     src: .tmux.conf
#     dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux.conf"
#     owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
#     mode: "0644"
